### PR TITLE
Add missing run_exports in cuda-cupti-dev

### LINKED ISSUE #9: Presence or absence of run_exports in `cuda-cupti-dev`
### Comment:

Hello @conda-forge/cuda , 
   I am experiencing a runtime failure due to a missing cuda-cupti package in jax compiled against `cuda` 12. I noticed that jax is compiled against `cuda-cupti-dev` package (see https://github.com/conda-forge/jaxlib-feedstock/blob/f24232396c4a2671e2efe879e22d19f4d83a814a/recipe/meta.yaml#L57), but `cuda-cupti-dev` , even if it contains headers and a shared library, does not contain any kind of `run_exports`. Is this intentional?

xref: https://github.com/conda-forge/conda-forge.github.io/issues/1963

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/conda-forge/cuda-cupti-feedstock/issues/9

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Review by vyasr — APPROVED** [review]
Yup this looks like an oversight on our part. Thanks!

**Review by bdice — APPROVED** [review]
Thanks for this fix!

As a note: I double-checked the SONAME / version compatibility of cupti. Prior to CUDA 12, linking to `libcupti` would break CUDA Enhanced Compatibility (runtime compatibility within the same major version) because it required the same major.minor version of CUDA. It seems that restriction has been lifted in CUDA 12.0 and later. That would've meant we needed different compatibility rules here but I think we are all good.

**Comment by vyasr** [comment]
We're doing a bit more investigation here as to whether there are issues with CEC in the rest of the dependency tree here.

**Comment by vyasr** [comment]
There are some subtleties around usage of cupti because some of its features involve other packages like nvperf that do not fully support CEC yet, and would therefore necessitate different pinnings in the run export. However, standalone usage of cupti is safe, so we're good with merging this PR for now and improving documentation of those edge cases over time.

**Comment by traversaro** [comment]
> There are some subtleties around usage of cupti because some of its features involve other packages like nvperf that do not fully support CEC yet, and would therefore necessitate different pinnings in the run export. However, standalone usage of cupti is safe, so we're good with merging this PR for now and improving documentation of those edge cases over time.

Thanks a lot!

**Pull request merged**
